apiVersion: tempo.grafana.com/v1alpha1
kind: TempoMonolithic
metadata:
  name: tempo
  namespace: istio-system
spec:
  storage:
    traces:
      backend: memory
      size: 1Gi

  ingestion:
    otlp:
      grpc:
        enabled: true
      http:
        enabled: true

  jaegerui:
    enabled: true
    route:
      enabled: true
      termination: edge
    ingress:
      enabled: false

  resources:
    requests:
      memory: "512Mi"
      cpu: "250m"
    limits:
      memory: "1Gi"
      cpu: "500m"

  serviceAccount: tempo
